lyonjs/shortvid.io

.github/workflows/integration.yml
.github/workflows/render-talk.yml
pages/talk.tsx
src/Video.tsx
src/sponsor/Sponsor.tsx
src/sponsor/SponsorLogo.tsx
src/sponsor/SponsorOrgaLogo.tsx
src/sponsor/SponsorTitle.tsx
src/talk/Talk.tsx
src/talk/TalkSpeakerPicture.tsx
src/talk/TalkTitles.tsx

It was a bit of a shame to have not split sequence of Talk and Sponsor compositio
- split them
- add backgroundImg props to talk
- rename composition

refactor: split sequences of talk and sponsor

---

pages/talk.tsx
pnpm-lock.yaml
src/talk/Talk.tsx
src/talk/TalkTitles.tsx

We want to upgrade the Talk generator 🏭
Adding more style + Fix some bugs with the fontSize 🔠
Check the preview + diff ✅

feat: customize talk generator

---

package.json
pnpm-lock.yaml

We have some WebStorm warning about eslint
Downgrade version ⬇️
CI ✅

chore: downgrade eslint

---

pages/_app.jsx
pages/app.css
pages/index.tsx
pages/sponsor.tsx
pages/talk.tsx
src/components/input.tsx

We want to enhance design 🤩
Adding more style !
Check the preview + diff ✅

feat: customize app design

---

pages/app.css
src/components/input.tsx

- css magic
- check right align on the form

style: small fixes on form alignment

---

pages/app.css
pages/index.tsx
pages/sponsor.tsx
pages/talk.tsx
pnpm-lock.yaml
src/components/Code.tsx
tsconfig.json

- Want to add an animation to indicate to the user that the current command is in the pastebin
- Add more information
- mutualize duplicated code
- title and command generation is now directly defined in the Code component
- add animation on click
- use vercel preview and click

feat(code): enhance code block

---

pages/_app.jsx
pages/app.css

feat(footer): add simple footer

---

pages/_app.jsx
pages/app.css

- add link of github repository
- change site description
- add link to remotion and all
- change style of button and link

feat(chapo): enhance design of chapo

---

pages/app.css

Site was not usable on small device due to page layout, this PR fixes that

fix: fix style for device < 768px

---

package.json
pages/index.tsx
pnpm-lock.yaml
src/Video.tsx
src/components/ImageBackground.tsx
src/components/hooks/useLottie.tsx
src/meetup/Meetup.tsx
src/meetup/MeetupDate.tsx
src/meetup/MeetupLogo.tsx
src/meetup/MeetupPresentation.tsx
src/meetup/MeetupTitle.tsx
src/meetup/Register.tsx

I want to enhance the meetup video generator by using Lottie and more animations
- Adding Lottie 📽
- Adding more animation
Check preview and code 😊

feat: Update meetup generator

---

pages/_app.jsx
pnpm-lock.yaml

feat: add emoji in navigation

---

src/components/hooks/onInputChange.ts
src/components/input.tsx

Found out we had a lot of warning in the console output of build, this fixes them.

chore: fix typings errors on Input element

---

pages/_app.jsx
src/components/ActiveLink.tsx

Wanted to challenge myself by removing duplicated code and extending Next Component
- create custom component `ActiveComponent`

refactor: use dedicate component for active link

---

pages/index.tsx
pages/sponsor.tsx
pages/talk.tsx
src/components/Code.tsx
src/components/hooks/onInputChange.ts
src/components/input.tsx

I did break rendering of the next website by forcing input type to be string and overriding default value to `''`.
This caused the background image to be undefined by default.
This PR repare that.
- define a generic type for onInputChange hook
- check CI step on `test`
- check NextJS app

fix: fix typing and default values

---

package.json
pages/_app.jsx
pages/app.css
pages/index.tsx
pages/sponsor.tsx
pages/talk.tsx
pnpm-lock.yaml
postcss.config.js
src/components/Code.tsx
src/components/input.tsx
styles/globals.css
tailwind.config.js

We want to give a try to Tailwind
Related to #34 
Follow tutorial of how to setup tailwind https://tailwindcss.com/docs/guides/nextjs
Use tailwind for some element

chore: setup basic configuration and style with tailwind

---

pages/_app.jsx
pages/index.tsx
pages/meetup.tsx
pnpm-lock.yaml
pnpm-workspace.yaml

#43 
- simple implementation for now, we could manage to do better

feat: create an example page on home

---

pages/meetup.tsx
pages/sponsor.tsx
pages/talk.tsx
src/Video.tsx
src/components/Code.tsx

Found out the generated command had issues:
- the notification message was added in the clipboard dans did not want that
- all the props were not updated
- pass props to an utility object in order not to miss anything
- reshape div of code element to only get the content, not the notification
- modify one video page and see that command is updated

fix: command generation with all props

---

src/components/Title.tsx
src/talk/TalkSpeakerPicture.tsx

Update some style and align speaker picture
Update components with the right style
Check preview 👀

fix: update style for title and alignment

---

src/event/Event.tsx
src/meetup/Meetup.tsx
src/sponsor/Sponsor.tsx
src/talk/Talk.tsx

There are some bugs when generating the video if some elements are off the screen during an animation 🐛
Hide the overflow on the different compositions
Try to render a video with this changes 🤷🏼‍♂️

fix: change overflow to prevent animation bug

---

package.json
pages/_app.jsx
pages/global.d.ts
pages/snowcamp.tsx
pnpm-lock.yaml
src/components.tsx
src/components/Code.tsx
src/snowcamp/Details.tsx
src/snowcamp/Snowcamp.tsx
src/snowcamp/Speakers.tsx

We need to integrate the snowcamp video generator on the application 🥳
- Adding new route
- Adding react-json-editor-ajrm to have a new json input
- Fix render command line to take quotes ( ' ) into account
Check the preview !

feat: adding snowcamp generator in app

---

src/components/ActiveLink.tsx

We have an error on app link click when we use next link.
I don't have time to dig the issue with the client/server diff, so let use SSG mode only.
- move Link usage to basic `a`
- check that you don't have diff error when switching

fix(website): fixup react error

---

generate-from-file.js
src/Video.tsx
src/conference/touraineTech2023/BigSpeakers.tsx
src/conference/touraineTech2023/Replay.tsx
src/conference/touraineTech2023/Title.tsx
src/conference/touraineTech2023/Type.tsx
src/conference/touraineTech2023/replays.json
src/talk/TalkSpeakerPicture.tsx

Related to last discussion in https://github.com/lyonjs/social-video-generator/discussions/104
- Duplicate some componant for now, we definitely need to define more extendable componant

feat: add video replay template for touraine tech

---

package.json
pnpm-lock.yaml

Some versions have not been updated by renovate 🤷🏼
Just update packages ! 👌🏼

chore(deps): update remotion shapes and google-fonts

---

pages/replay.tsx
src/Video.tsx
src/components/Code.tsx
src/conference/lyonJS/BigSpeakers.tsx
src/conference/lyonJS/Details.tsx
src/conference/lyonJS/LeftTriangle.tsx
src/conference/lyonJS/Logo.tsx
src/conference/lyonJS/LogoSponsor.tsx
src/conference/lyonJS/Replay.tsx
src/conference/lyonJS/RightTriangle.tsx
src/conference/lyonJS/Title.tsx
src/conference/lyonJS/Type.tsx

We want to make the video of the LyonJS replay 🤷🏼‍♂️
Add the video for LyonJS replay + config in next app (A lot of code duplication but this will be fixed later)
Look at the Next application, you should see the LyonJS video in `/replay` !

feat(replay): setup LyonJS video for replays

---

pages/_app.jsx

We need to add vercel banner in every site footer page for sponsorship requirements

feat(footer): add vercel banner in footer

---

.github/workflows/integration.yml
.github/workflows/render-meetup.yml
.github/workflows/render-sponsor.yml
.github/workflows/render-talk.yml

We want to make our CI workflow faster and more resilient with the usage of dependency caching
- add cache on each setup node 
- verify CI status

ci: use pnpm cache during workflows

---

src/conference/mixit2023/Speakers.tsx
src/conference/mixit2023/generateJSON.mjs
src/conference/mixit2023/talks.json

Found out the formatted time was not correct. 
We want to use `[0-23]` format for our
Also some speaker don't have a profile picture in the API we should provide a default one
- fix usage of `date-fns`
- pass default value to image
- Video with default image, if @CruuzAzul you found a better default free avatar, I let you suggest it
https://user-images.githubusercontent.com/6263857/221032218-a9eb68cb-5516-4802-b104-cbfde63df76c.mp4
- Found out some speaker names are too long (we will need ad dedicate fix for that
https://user-images.githubusercontent.com/6263857/221032421-d3aac4ab-e43e-4d04-9621-46bc755caa97.mp4

fix(mixit): fixup date used inside video

---

src/Video.tsx
src/conference/alpescraft/AlpesCraft.tsx
src/conference/alpescraft/Details.tsx
src/conference/alpescraft/Speakers.tsx
src/conference/alpescraft/SpeakersName.tsx
src/conference/alpescraft/Title.tsx

AlpesCraft also want to present there speakers -> #147 
I've added a condition that if there is a speaker data, it will not show the logo but the speaker.s. Same for the time information.
- You can change the data on src/video and see the differences when running `pnpm start`

feat(conference): completed alpescraft video by adding speakers and time

---

.github/workflows/check-pr-title.yml

We want to have consistency between all our PR titles
Use a github action to check that ! (plus it's good publicity for Antoine 😅)
Check the CI ! ✅

ci(pr-title): adding workflow to check pr title

---

package.json
pages/_app.jsx
pnpm-lock.yaml

Add tracking on the web application
- use vercel pro plan on analytics

feat(analytics): add vercel analytics on the website

---

.github/ISSUE_TEMPLATE/feature-request-🚀.md
.github/ISSUE_TEMPLATE/feature-request.md

We want to add issue template for feature request on the project
Use github to add a new template (I got a template similar to the one in remotion)
Check diff !

chore(issues): adding issue template for feature request

---

.github/ISSUE_TEMPLATE/bug-report.md

We want to add issue template for bug request on the project
Use github to add a new template (I got a template similar to the one in remotion)
Check diff !

chore(issues): adding issue template for bug request

---

.github/ISSUE_TEMPLATE/template-request.md

We want to add issue template for template video request on the project
Use github to add a new template (I got a template similar to the one in remotion)
Check diff !

chore(issues): adding issue template for template request

---

src/conference/lyonJS/LayerOneSpeaker.tsx
src/conference/lyonJS/LayerTwoSpeaker.tsx

fix(layers): update layer design & adding sponsor logo

---

pages/conferences/[conferenceName].tsx
src/conference/data/defaultValues.js

After changing some of our profile pictures on the network our data is no longer up to date
While waiting to put default values, or hosted images, I updated the datas
Check the preview in the conference section

fix(data): update sample image data

---

.github/workflows/pr-labeler.yml

We want to automatically track the size of PR submitted in review
- use PR size labeler project

chore(ci): setup PR size labeler

---

CONTRIBUTING.md

Add the correct value for input command
Testing :)
try in windows :)

docs(contributing): add input for console local props

---

remotion/compositions/showcases/touraineTech2023/BigSpeakers.tsx
remotion/compositions/showcases/touraineTech2023/Replay.tsx
remotion/compositions/showcases/touraineTech2023/Speakers.tsx
remotion/compositions/showcases/touraineTech2023/SponsorTouraineTech2023.tsx
remotion/compositions/showcases/touraineTech2023/TalkTitle.tsx
remotion/compositions/showcases/touraineTech2023/TouraineTech2023.tsx

i've updated the TouraineTech compositions with the atom text

fix(showcases): fix tourainetech video

---

remotion/compositions/showcases/mixit2023/Mixit2023.tsx
remotion/compositions/showcases/mixit2023/Speakers.tsx
remotion/compositions/showcases/mixit2023/TalkTitle.tsx

i've updated the Mixit composition with the atom text

fix(showcases): fix mixit video

---

remotion/compositions/showcases/very-tech-trip/Speakers.tsx
remotion/compositions/showcases/very-tech-trip/TalkTitle.tsx
remotion/compositions/showcases/very-tech-trip/VeryTechTrip.tsx

i've updated the VeryTechTrip composition with the atom text

fix(showcases): fix verytechtrip video

---

remotion/compositions/showcases/devoxx2023/Devoxx2023.tsx
remotion/compositions/showcases/devoxx2023/SpeakerName.tsx
remotion/compositions/showcases/devoxx2023/Speakers.tsx
remotion/compositions/showcases/devoxx2023/TalkTitle.tsx

i've updated the Devoxx composition with the atom text

fix(showcases): fix devoxx video

---

remotion/compositions/showcases/lyonJS/BigSpeakers.tsx
remotion/compositions/showcases/lyonJS/LayerOneSpeaker.tsx
remotion/compositions/showcases/lyonJS/LayerTitle.tsx
remotion/compositions/showcases/lyonJS/LayerTwoSpeaker.tsx
remotion/compositions/showcases/lyonJS/Replay.tsx
remotion/compositions/showcases/lyonJS/TalkTitle.tsx

i've updated the LyonJs compositions with the atom text

fix(showcases): fix lyonjs video and layers

---

remotion/compositions/showcases/snowcamp/Snowcamp.tsx
remotion/compositions/showcases/snowcamp/Speakers.tsx
remotion/compositions/showcases/snowcamp/TalkTitle.tsx

i've updated the Snowcamp composition with the atom text

fix(showcases): fix snowcamp video

---

remotion/compositions/templates/meetup/MeetupTitle.tsx
remotion/compositions/templates/sponsor/SponsorMap.tsx
remotion/compositions/templates/sponsor/SponsorName.tsx

By updating the title with the text atom, the templates must be updated too with the good uses. If not the compositions should be broken in some points (speakers name or titles)
i've updated the Templates compositions with the atom text and title

fix(showcases): fix templates videos

---

src/app/Code.tsx

Due to the new app, the genreated code doesn't work when copy pasted in a terminal.
Check [this URL](https://social-video-generator-git-fix-link-lyonjs.vercel.app/showcases/conferences/Devoxx)

fix(app): update generated link with new app structures

---

README.md
app/layout.tsx
app/page.tsx
package.json
src/app/Code.tsx
src/app/Header.tsx
src/app/RootLayout.tsx

```
git remote set-url origin git@github.com:lyonjs/shortvid.io.git
```
Now that we have changed the name and url of the project we need to update everything in the project ! 🥳
Webstorm ✅
See that the whole application works and all the links too !

chore(app): update all the project with shortvid.io

---

app/templates/silhouette/page.tsx
remotion/compositions/templates/Templates.composition.tsx
remotion/compositions/templates/silhouette/Silhouette.composition.tsx
remotion/compositions/templates/silhouette/Silhouette.tsx
remotion/compositions/templates/silhouette/Silhouette.type.ts
remotion/compositions/templates/silhouette/SilhouetteLogo.tsx
remotion/compositions/templates/silhouette/SilhouettePicture.tsx
remotion/compositions/templates/silhouette/SilhouetteTitle.tsx

I worked on a template few weeks ago for a talk I did not have the opportunity to give, but the template still exists ! 👍🏻 
Let add it to our catalog
- add template
- add new page to display it
https://social-video-generator-git-template-silhouette-lyonjs.vercel.app/templates/silhouette

feat(templates): add a new generic template

---

remotion/design/atoms/Atoms.composition.tsx

the build send an error because of a missing import
import the staticFIle method

fix(atom): correct backgroundfiller default props

---

src/app/Code.tsx

We want to be able to track usage of local generation of video locally in the website
- use `@vercel/analytics` feature of track event

feat(tracking): track usage of local generation

---

app/templates/event/page.tsx
remotion/compositions/templates/event/Event.tsx
remotion/compositions/templates/event/EventTitle.tsx
src/app/forms/FontPicker.tsx
src/app/hooks/onInputChange.ts
src/data/fonts.js

We want to allow the users to select their font on the compositions
I created a select input that list the google fonts, when you select one it changes the title on the Event template (Only on the event template it's just a POC because it will be refacto with the issue #206)
- You can test the input ont the preview https://shortvid-git-290-create-font-picker-atom-lyonjs.vercel.app/templates/event

feat(font): create font-picker

---

generate-from-file.js
remotion/compositions/showcases/camping-des-speakers/CampingDesSpeakers.composition.tsx
remotion/compositions/showcases/camping-des-speakers/talks.json

We have some bug with the video generation
Update script + composition
Check the code 😊

fix(template/cds): update duration and data

---

styles/globals.css

In order to redesign the site we need a new graphic identity.
Adding colour variables for primary-color.
Check the code

style(setup): adding purple variants in globals.css

---

src/app/Code.tsx

The popup that is displayed after a copy on the click of the code for the video generation.
I've changed the tailwind css class on `Code.tsx`
- check the code and try copy the cmd on the preview

fix(color): update code copy popup color

---

__test__/app/footer.test.tsx
jest.config.js
package.json
pnpm-lock.yaml

To test the footer and be sure that every elements is displayed
I created `footer.test.tsx` under `__test__/app` and completed the test.
- Read the code and see if the check is green

feat(test): add test on footer component

---

package.json
pnpm-lock.yaml

Reverts lyonjs/shortvid.io#366

Revert "chore(deps): update dependency postcss to v8.4.24"

---

app/page.tsx

Update the style for the homepage
Update player width and remove unused style
Check the preview

style(home): fix video demo size & remove controls

---

CONTRIBUTING.md
Dockerfile

I add the ability to use Docker 🐳  to use shortvid
See the Contributing.md dedicated section.
Run the commands 😄

feat(generation): add Dockerfile to support docker ✨

---

src/data/sideBarConfig.ts

We want a config file for the sidebar to be able to automatically generate the routing and the videos lists.
I created a file under `src/data/sideBarConfig.ts` and add the routing for the videos to an object.
- check the file and see if everything that is required for the routing is in.

feat(app): create sidebar routing config

---

app/showcases/conferences/[conferenceName]/page.tsx
pnpm-lock.yaml
remotion/compositions/showcases/volcamp/Volcamp.composition.tsx
remotion/compositions/showcases/volcamp/Volcamp.tsx
remotion/compositions/showcases/volcamp/components/Eruption.tsx

With the aim of sharing the video template, we want to correct and clean up the last little details
Update styles
Check the preview ✅

style(volcamp): fix volcamp video for prod

---

__test__/app/footer.test.tsx
app/templates/layers/page.tsx
app/templates/silhouette/page.tsx
src/app/Footer.tsx
src/app/RootLayout.tsx
styles/app/layout/footer.module.css

to remove duplicated theme input
updated the layout and styles
- Check tests and code
- Check preview

feat(sidebar): refacto layout 

---

package.json
pnpm-lock.yaml

https://twitter.com/timneutkens/status/1675933610992345090?s=61&t=Z1sYIO2-PaO2T2G0umfN6g
Update next to the new version 📦
Check the preview + try the dev mode

chore(deps): update dependency next to v13.4.10

---

app/templates/events/event/page.tsx
app/templates/layers/layers/page.tsx
app/templates/meetups/meetup/page.tsx
app/templates/replays/replay/page.tsx
app/templates/talks/silhouette/page.tsx
src/app/types/template.types.ts
src/data/config/compositionsConfig.ts

We need to fix the routing after updating the sidebar config
Arrange each page in default folder
Check the preview

fix(routing): update sidebar config

---

app/layout.tsx
app/page.tsx
src/app/RootLayout.tsx
styles/app/layout/footer.module.css

We only want to display the footer in the homepage
- Remove `<Footer />` from the `RootLayout` 
- Adding `<Footer />` on the homepage
- Fix style 🎨
Check the preview 👀

feat(app): only display footer on homepage

---

app/templates/talks/talkBranded/page.tsx
src/app/forms/Form.tsx
src/app/forms/inputDate.tsx
src/app/hooks/useInputDateChange.ts

To avoid all the duplication on the pages
I updated the component `Form` to take a config object and generate the inputs from it
- check the code

feat(app): poc refacto pages with sidebar right

---

src/app/RootLayout.tsx
styles/app/components/sidebar/resizeWrapper.module.css
styles/app/layout/main.module.css

To show the sidebar even when the user scroll
I set the sidebar wrapper in position sticky
check the preview

feat(app): fixed sidebar

---

app/templates/events/event/page.tsx
app/templates/layers/layers/page.tsx
app/templates/layout.tsx
app/templates/meetups/meetup/page.tsx
app/templates/sponsors/sponsor/page.tsx
app/templates/sponsors/spotlightNewSponsor/page.tsx
app/templates/talks/silhouette/page.tsx
app/templates/talks/talk/page.tsx
app/templates/talks/talkBranded/page.tsx
src/app/forms/Form.tsx
src/app/forms/FullScreenButtons.tsx
src/app/forms/inputDate.tsx
src/app/hooks/useInputDateChange.ts
styles/app/components/sidebar/resizeWrapper.module.css
styles/app/components/sidebar/sidebar.module.css
styles/app/layout/main.module.css

To have a better UX/UI experience for mobile users
I added some style and components to the pages
- check the code
- check the preview

feat(app): layout responsive with sidebar right

---

styles/app/common/form.module.css
styles/app/components/sidebar/nav.module.css
styles/app/components/sidebar/resizeWrapper.module.css

To fix the bug when folding the sidebar the width stay the same and to fix the scrollbar overflows that where not good
updated a variable name that was forgotten and overflow styles
check code

fix(sidebar): resize an scroll overflow

---

src/app/components/sidebar/ResizeWrapper.tsx
styles/app/components/sidebar/resizeWrapper.module.css
styles/app/layout/main.module.css

To fix the issue that if we fold the nav sidebar it save the preferences and apply it to the form sidebar
i've moved the style definition to a better file
- check the preview

fix(app): fold min width applied in both sidebar

---

server.mjs

To be able to generate video on Vercel previews
I added a corresponding regex for the preview url
- check the regex

feat(serve): add preview regex for cors

---

app/templates/events/event/page.tsx

The font are not rendered so for now we just remove the input until the bug is fixed
remove the font selector from the form
- check the code
- check the preview

fix(app): remove font picker

---

remotion/design/atoms/Text.tsx

A modifications was past and should have not
I reset the font assignation to the component Text
Check the preview and code

fix(app): default font not rendered

---

styles/app/common/buttons.module.css
styles/globals.css

To have more sexy buttons
I updated the styles on the backgrounds and hover effects of the primary and secondary buttons
- check the preview

feat(app): update styles for buttons

---

__test__/app/landing/contact.test.tsx
__test__/app/landing/footer.test.tsx
__test__/app/landing/github.test.tsx
__test__/app/landing/hero.test.tsx
__test__/app/landing/partners.test.tsx
__test__/app/landing/sponsors.test.tsx
styles/app/common/buttons.module.css
styles/globals.css

To test the displayed components
I created a test for each section of the landing page
- check the preview and the tests codes

feat(test): refacto layout - add tests

---

remotion/compositions/showcases/devfestNantes/Android.tsx

In the android animation, the flash image appears at the beginning. What's more, it will be easier to loop the animation if the Android makes a complete animation and then disappears.
Change interpolate values 
Check the preview 👀 
🔗 https://shortvid-git-fix-android-anim-lyonjs.vercel.app/showcases/conferences/DevfestNantes

fix(template): update android animation to avoid flashing

---

remotion/compositions/showcases/campingDesSpeakers/components/TalkTitle.tsx
remotion/compositions/showcases/devfestNantes/Android.tsx
remotion/compositions/showcases/devfestNantes/Details.tsx
remotion/compositions/showcases/devfestNantes/DevfestNantes.composition.tsx
remotion/compositions/showcases/devfestNantes/DevfestNantes.tsx

We want to add all details in the composition (date, time and location)
- Create a new `Details` component using the `TalkDetails` molecule
- Adding animations
Check the preview 😊
🔗 https://shortvid-git-defest-nantes-details-lyonjs.vercel.app/showcases/conferences/DevfestNantes

feat(template): adding details component in default composition

---

app/templates/talks/talkBranded/page.tsx
remotion/compositions/templates/talk/branded/BrandedDetails.tsx
remotion/compositions/templates/talk/branded/TalkBranded.tsx
src/app/forms/Form.tsx
src/app/forms/selectInput.tsx

We want to update the Branded Talk template to set some props optionnal
Updates props ans types + add style
Check the preview

chore(template): set reccuring day optionnal

---

remotion/compositions/showcases/devfestNantes/DevfestNantes.composition.tsx
remotion/compositions/showcases/devfestNantes/DevfestNantesLoop.tsx
remotion/compositions/showcases/devfestNantes/Dino.tsx
remotion/compositions/showcases/devfestNantes/Logo.tsx

We want to make a new Devfest Nantes composition who will be able to loop to TV usage during event 
Adding animation back on all items
Check the preview or this video :
https://github.com/lyonjs/shortvid.io/assets/60877626/2e73f4f4-8f8a-4a3d-bb33-d461c6f371f2

feat(template): adding loop in DevfestNantes composition

---

app/showcases/conferences/[conferenceName]/page.tsx
src/data/config/showcases/devfestNantesConfig.ts

fix(showcase): update devfest nantes preview in app

---

__test__/app/components/ActiveLink.test.tsx

Test <ActiveLink /> component
I checked the activeLink class was in the list of classes applied by <ActiveLink /> on the `<a>` html tag.
`npm run test -- --no-coverage __test__/app/components/ActiveLink.test.tsx`
Fixing #350

test(ActiveLink): adding test to activeLink

---

remotion/compositions/showcases/devfestNantes/Android.tsx
remotion/compositions/showcases/devfestNantes/Details.tsx
remotion/compositions/showcases/devfestNantes/DevfestNantes.composition.tsx
remotion/compositions/showcases/devfestNantes/DevfestNantes.tsx
remotion/compositions/showcases/devfestNantes/DevfestNantesLoopTotem.tsx
remotion/compositions/showcases/devfestNantes/DevfestNantesPhrase.tsx
remotion/compositions/showcases/devfestNantes/Logo.tsx
remotion/compositions/showcases/devfestNantes/TalkTitle.tsx
remotion/compositions/showcases/devfestNantes/types/types.ts

We want a new composition to display a talk in vertical mode
- Adding new composition
- Adding `isTotemDisplayMode` to change animations on components according to the composition mode
Clone and test 😊
https://github.com/lyonjs/shortvid.io/assets/60877626/933d2ae3-504c-4e5c-9b82-8d12d847df6b

feat(template): adding totem option with a new composition

---

remotion/compositions/showcases/touraineTech/Details.tsx
remotion/compositions/showcases/touraineTech/TalkTitle.tsx

We need a shadow on our text on this template
Update style
Check the preview on the Touraine Tech template

fix(template/tt): fix shadow on template text

---

.github/workflows/integration.yml
package.json
pnpm-lock.yaml

chore(pnpm): fix pnpm version to 8

---

remotion/compositions/showcases/campingDesSpeakers/CampingDesSpeakers.composition.tsx
remotion/compositions/showcases/touraineTech/TouraineTech.composition.tsx
remotion/compositions/showcases/touraineTech/planning_remotion.json
remotion/compositions/showcases/touraineTech/replays.json
remotion/compositions/showcases/volcamp/Volcamp.composition.tsx
src/data/defaultValues.js

chore(data): fix typo in talk title value

---

app/showcases/conferences/[conferenceName]/page.tsx
src/data/config/showcases/devfestLilleConfig.ts
src/data/config/showcases/devfestNantesConfig.ts
src/data/config/sideBarConfig.ts

We have to fix compositionName for generation on the next app
Update compositionName
Check the app and try to generate a video

fix(app): update compositionName for generation

---

.github/workflows/deploy-editor.yml
Dockerfile.editor
package.json
remotion/compositions/templates/event/Event.tsx
remotion/design/atoms/Text.tsx

We decide with @CruuzAzul to remove the website shortvid.io made in Next.JS on this page https://shortvid.io/templates/talks/talk
We will replace it by deployed Remotion Studio on editor.shortvid.io
- remove usage of dynamic font loading. This is breaking the studio itself and the usage of it is very limited.
- Some compositions are certainly broken due to that
- add secrets to repository secrets
- add workflow to deploy the website on main branch 
Go on https://editor.shortvid.io

ci(editor): deploy editor workflow setup

---

remotion/compositions/templates/sponsors/Sponsors.composition.tsx
remotion/compositions/templates/sponsors/sponsors.types.ts
remotion/compositions/templates/sponsors/spotlightNewSponsor/SpotlightNewSponsor.tsx

We need to have zod schema for all compositions
- add schema

feat(remotion): add zod schema for sponsors

---

remotion/compositions/templates/meetup/Meetup.composition.tsx
remotion/compositions/templates/meetup/PosterLocation.tsx

When we organize meetup we often need to generate poster to indicate where the event will take place.
- add new Still template

feat(templates): add new template for Posters

---

remotion/compositions/showcases/snowcamp/Details.tsx
remotion/compositions/showcases/snowcamp/Speakers.tsx
remotion/compositions/showcases/snowcamp/TalkTitle.tsx

We need to update the font of speakers name on the snowcamp template

fix(template): font speaker name snowcamp
