lyonjs/shortvid.io

package.json, pages/_app.jsx, pages/event.tsx, pages/index.tsx, src/Video.tsx, src/components/LottieAsset.tsx, src/components/Paillettes.tsx, src/event/Event.tsx, src/event/EventTitle.tsx
We want to add an event video generator !
- Create new video generator with custom Payet 🎉
Check the preview 👀
=> feat: adding event video generator

pages/conferences/[conferenceName].tsx, src/components/site/NavBar.tsx, styles/globals.css
The select component was a bit crappy, I think it would be better to have a dedicate page URL for each Conference with which we work with.
- use getStaticPath and getStaticProps
Go on conference page and see the result
=> feat(site): handle each conference in dedicate page with URL

pages/conferences/[conferenceName].tsx, src/conference/mixit2023/Speakers.tsx
Not all videos will have the same length, but we want a correct display on the Next application
Adding a `durationInFrames` parameter 🥳 
(We could have put a default value but I don't know if it's useful knowing that it depends on the video)
Check the preview, you should see the entire Devoxx video !
=> fix(conferences): adding durationInFrames in template

pages/conferences/[conferenceName].tsx, src/Video.tsx, src/conference/alpescraft/AlpesCraft.tsx, src/conference/alpescraft/Title.tsx
To make the template easy access and customisable for users.
I've added the configuration for AlpesCraft in `pages/conferences/[conferenceName].tsx`.
I've also rebase from #156 to get the duration in frames for the composition
- You can run `pnpm dev` and go on the `conference` page, you should see a link on the list with the name **AlpesCraft**
- If you click on the link you should see the composition playing with the default data
=> feat(conference): add alpescraft video to webpage

package.json, pages/meetup.tsx, pages/talk.tsx, src/Video.tsx, src/components/EventLogo.tsx, src/components/LyonJSLogo.tsx, src/components/site/Header.tsx, src/components/site/forms/input.tsx, src/meetup/Meetup.tsx, src/meetup/MeetupLogo.tsx, src/meetup/MeetupPresentation.tsx, src/sponsor/SponsorOrgaLogo.tsx, src/talk/Talk.tsx
Open the project to other meetups by allowing them to use their logo instead of the LyonJs's one
Add an input field in the Talk and Meetup generation page where people can add a static URL (fallback to LyonJs logo if not present)
- Go to `/meetup` and fill the last input value with a valid image URL
- (Optionnally) generate the video
Do the same for `/talks` :)
=> feat(talks|meetups): add dynamic event logo possibility

src/Video.tsx, src/conference/lyonJS/GreenScreen.tsx, src/conference/lyonJS/LayerOneSpeaker.tsx, src/conference/lyonJS/LayerTitle.tsx, src/conference/lyonJS/LayerTwoSpeaker.tsx
If could be could if the Layers can have a title as prop
I only add title for layer with one or two speakers, in full screen there is no space available for title.
=> feat(lyonjs): add title for layers

pages/_app.jsx, pages/layer/fullscreen.tsx, src/conference/lyonJS/GreenScreen.tsx
It could be could if we can directly point to an URL with query param for pages
I had en endpoint to `/layer/fullscreen` with two query params:
- `mode` which can be 'one', 'two' or 'full'
- `title` to display the title of the PR
I had to prevent default page layout by adding a property on the component `noLayout` directly, used on the _app.tsx directly
- https://social-video-generator-git-fullscreen-layers-lyonjs.vercel.app/layer/fullscreen?title=Project%20XState
- https://social-video-generator-git-fullscreen-layers-lyonjs.vercel.app/layer/fullscreen?title=Project%20XState&mode=two
- https://social-video-generator-git-fullscreen-layers-lyonjs.vercel.app/layer/fullscreen?title=Project%20XState&mode=full
=> feat(lyonjs): add page to display layer in fullscreen

remotion/Video.tsx, remotion/compositions/templates/Templates.composition.tsx
The remotion preview don't have the same folder management as in the project. It will be better to find the components if both organisations match.
I've updated the file `remotion/video.tsx` and split in folder the imports following the project organisation.
- You can run `pnpm start` and compare the organisation with the one in the project.
=> chore(remotion): reorganise remotion preview to fit project organisation

remotion/compositions/showcases/alpescraft/AlpesCraft.composition.tsx
Change AlpesCraft composition id from 'Alpescraft' to 'AlpesCraft'.
This case issue causes an error when copy pastes the pnpm command from the website:
```
An error occurred:
Error: Cannot find composition with ID "AlpesCraft". Available composition: Sponsor, SponsorWithoutLogo.....
```
=> fix(showcase): AlpesCraft composition id

package.json, pnpm-lock.yaml, remotion/design/atoms/Atoms.composition.tsx, remotion/design/atoms/BackgroundCircleNoise.tsx, remotion/design/atoms/BackgroundNoise.tsx
In future templates we will use this background.
I've got the component from the doc : https://www.remotion.dev/docs/noise-visualization
and add it to the atoms list.
- You can check the component under `Design/Atoms/BackgroundCircleNoise`
=> feat(atoms): create atom background circle noise

remotion/compositions/showcases/alpescraft/Details.tsx, remotion/compositions/showcases/devoxx2023/Details.tsx, remotion/compositions/showcases/lyonJS/Details.tsx, remotion/compositions/showcases/mixit2023/Details.tsx, remotion/compositions/showcases/snowcamp/Details.tsx, remotion/compositions/showcases/touraineTech2023/Details.tsx, remotion/compositions/showcases/touraineTech2023/Type.tsx, remotion/compositions/showcases/very-tech-trip/Details.tsx
The molecule was created but on many compositions it wasn't used
i've updated the compositions with the molecules details and iconWithCaption
- You shouldn't see lottie icons anymore but instead it's iconify icons
=> feat(showcases): use details and icon with caption molecules

app/templates/sponsor/page.tsx
It's cool to have the pre-fill on the talk page, so why not using it on the others
I've updated the page `app/templates/sponsor/page.tsx` with the copyUrlButton and the default values from the query params in the url
- On the preview you can try the feature on the page `Sponsor`, you should be able to copy the url with your modifications saved in the query params.
=> feat(webapp): updated sponsor page with copy url button #281

app/templates/meetup/page.tsx
It's cool to have the pre-fill on the talk page, so why not using it on the others
I've updated the page `app/templates/meetup/page.tsx` with the copyUrlButton and the default values from the query params in the url
- On the preview you can try the feature on the page `Meetup`, you should be able to copy the url with your modifications saved in the query params.
=> feat(webapp): updated meetup page with copy url button #281

package.json, pnpm-lock.yaml, remotion/compositions/templates/talk/Talks.composition.tsx, remotion/compositions/templates/talk/branded/BrandedDetails.tsx, remotion/compositions/templates/talk/branded/BrandedHost.tsx, remotion/compositions/templates/talk/branded/BrandedLocation.tsx, remotion/compositions/templates/talk/branded/BrandedLogo.tsx, remotion/compositions/templates/talk/branded/BrandedSpeaker.tsx, remotion/compositions/templates/talk/branded/BrandedSpeakerInfos.tsx, remotion/compositions/templates/talk/branded/BrandedTitle.tsx, remotion/compositions/templates/talk/branded/TalkBranded.tsx
New template for talk with custom logo, speaker and color with. Customised with the GDG design by default, see the discussion about it here #219 .
I created the compositions and it's different elements animated
- You can check the video on the remotion preview under `Templates/Talk/TalkBranded`
=> feat(templates): create branded talk template

app/showcases/conferences/[conferenceName]/page.tsx, package.json, pnpm-lock.yaml, src/app/NavBar.tsx
We want to add the new created showcase for `Camping Des Speakers` to the app.
I added the showcase to the configuration and add some update for the fps and the defaultProps that are different in the new one.
- You can check on the preview if everything is ok, you should see the showcase and on it's props it should have the company. 
- Be sure that the company is on the command line, the video and on the json preview but only in this showcase.
=> feat(app): add showcase camping des speakers

app/templates/brandedTalk/page.tsx, src/app/hooks/onInputChange.ts
To fix the copy url button on the new branded talk page
The page couldn’t be saved because of the date that was in a wrong format so i've handle the formatting on the encoded object and on the recuperation of the query param
on the preview try to copy/paste the url with params
=> fix(webapp): copy url with date not working

app/showcases/conferences/[conferenceName]/page.tsx, src/app/NavBar.tsx
After creating the showcase video, we add it in the app to make it available for the users to generate their own videos.
I've add the config of the Volcamp video to the `shocases/[conferenceName]/page.tsx` page and updated the navLink to make it point to this video in first.
- Check the video on the preview
- Check the code
=> feat(app): add volcamp video to showcases

app/showcases/conferences/[conferenceName]/page.tsx, app/templates/replay/page.tsx, remotion/compositions/showcases/alpescraft/AlpesCraft.tsx, remotion/compositions/showcases/alpescraft/Speakers.tsx, remotion/compositions/showcases/devoxx/Devoxx2023.tsx, remotion/compositions/showcases/devoxx/Speakers.tsx, remotion/compositions/showcases/lyonJS/BigSpeakers.tsx, remotion/compositions/showcases/lyonJS/Replay.tsx, remotion/compositions/showcases/mixit/Mixit2023.tsx, remotion/compositions/showcases/mixit/MixitIntroTalk.tsx, remotion/compositions/showcases/mixit/Speakers.tsx, remotion/compositions/showcases/snowcamp/Snowcamp.tsx, remotion/compositions/showcases/snowcamp/Speakers.tsx, remotion/compositions/showcases/touraineTech/BigSpeakers.tsx, remotion/compositions/showcases/touraineTech/Replay.tsx, remotion/compositions/showcases/touraineTech/Speakers.tsx, remotion/compositions/showcases/touraineTech/TouraineTech2023.tsx, remotion/compositions/showcases/veryTechTrip/Speakers.tsx, remotion/compositions/showcases/veryTechTrip/VeryTechTrip.tsx, remotion/compositions/showcases/volcamp/components/Talk.tsx, remotion/compositions/templates/layers/LayerFullScreen.tsx, remotion/compositions/templates/layers/LayerOneSpeaker.tsx, remotion/compositions/templates/layers/LayerTwoSpeaker.tsx, remotion/compositions/templates/layers/layers.types.ts, remotion/types/defaultProps.types.ts, src/app/Code.tsx
There was a lot of types that where duplicated or miss-named.
I renamed the folder `Conferences.types.ts` to `DefaultProps.types.ts` and updated the types where they have been used. I also remove the duplicated types similar to the default props ones.
- Check the code
- See if there is duplications left
=> feat(types): refacto types

__test__/app/sidebar.test.tsx, src/app/hooks/useSidebarPreferences.ts, src/context/SidebarContext.tsx
We want to save the preferences of the user about the sidebar
I created a hook that get and set a local storage variable to save the fold value of the sidebar
- Check the code
- Check the preview
=> feat(app): saving sidebar folded preference

src/app/components/sidebar/ResizeWrapper.tsx
The `stopResize` function makes the dependencies of useEffect Hook change on every render.
Move the function inside the useEffect callback.
Just check the app and try to resize the sidebar 😊
=> refactor(resize): avoid useEffect dependencies change on every render

src/app/Code.tsx, src/app/utils/encodeObjectValues.ts
When a value is undefined it is not passed to the renderer, so the default values are used.
QuickWin to fix it, but we'll have to find another solution to clean it up.
check the preview and try to render a video with null values
=> chore(template): set reccuring day optionnal

app/templates/talks/talkBranded/page.tsx, remotion/compositions/templates/talk/Talks.composition.tsx, remotion/compositions/templates/talk/branded/BrandedDetails.tsx, remotion/compositions/templates/talk/branded/BrandedLocation.tsx, remotion/compositions/templates/talk/branded/BrandedLogo.tsx, remotion/compositions/templates/talk/branded/BrandedSpeaker.tsx, remotion/compositions/templates/talk/branded/BrandedSpeakerInfos.tsx, remotion/compositions/templates/talk/branded/BrandedTitle.tsx, remotion/compositions/templates/talk/branded/TalkBranded.tsx, remotion/compositions/templates/talk/talks.types.ts, src/app/types/template.types.ts, src/data/config/compositionsConfig.ts, src/data/config/templates/talkBrandedConfig.ts
In order to have cleaner types for our compositions and use Remotion's new editing features, we want to use Zod
Check the preview that the talk branded video is working as it was before + clone the projet to check that the remotion editor is working or check the video :
https://github.com/lyonjs/shortvid.io/assets/60877626/225a2257-f08b-482d-8e4e-bc7df6cf67bd
ℹ️ There's a warning about saving default props, I've spotted the problem and I'm going to create an issue directly in remotion.
=> feat(zod): adding zod schema on talk branded compositions

server.mjs
Be able to render still image from a composition 
Add a new route for frame/still rendering, based on the video output
```curl -X POST http://localhost:8000/frame/Talk/-1 --output toto1.png```
=> feat(server): add frame/still rendering in the API

app/templates/talks/talkBranded/page.tsx, remotion/compositions/templates/talk/Talks.composition.tsx, remotion/compositions/templates/talk/branded/BrandedSpeaker.tsx, remotion/compositions/templates/talk/branded/BrandedSpeakerInfos.tsx, remotion/compositions/templates/talk/branded/TalkBranded.tsx, remotion/compositions/templates/talk/talks.types.ts, src/data/config/templates/talkBrandedConfig.ts
Be able to display at least, 2 speakers for a single talk via the TalkBranded template.
Add a `speakers : z.optional([])` to the TalkBranded, pass the `speaker : {}` to `speaker : z.optional({})` making it  optional. 
To adjust the design, I've added a few more props to a few components making them more configurable. 
Result here: 
https://github.com/lyonjs/shortvid.io/assets/662377/c7b00adb-45fd-4172-b813-c30f782b5ced
=> feat(template): support multi-speaker on the TalkBranded template

remotion/compositions/showcases/alpescraft/AlpesCraft.composition.tsx, remotion/compositions/showcases/alpescraft/AlpesCraft.tsx, remotion/compositions/showcases/devfestLille/DevfestLille.composition.tsx, remotion/compositions/showcases/devfestLille/DevfestLille.tsx, remotion/compositions/showcases/devfestNantes/DevfestNantes.composition.tsx, remotion/compositions/showcases/devfestNantes/DevfestNantes.tsx, remotion/compositions/showcases/devfestNantes/DevfestNantesLoop.tsx, remotion/compositions/showcases/devfestNantes/DevfestNantesLoopTotem.tsx, remotion/compositions/showcases/devoxx/Devoxx.composition.tsx, remotion/compositions/showcases/devoxx/Devoxx2023.tsx, remotion/compositions/showcases/devoxx/Devoxx2024.tsx, remotion/compositions/showcases/mixit/Mixit.composition.tsx, remotion/compositions/showcases/mixit/Mixit.tsx, remotion/compositions/showcases/mixit/MixitIntroTalk.tsx, remotion/compositions/showcases/showcases.types.ts, remotion/compositions/showcases/snowcamp/Snowcamp.composition.tsx, remotion/compositions/showcases/snowcamp/Snowcamp.tsx, remotion/compositions/showcases/touraineTech/TouraineTech.composition.tsx, remotion/compositions/showcases/touraineTech/TouraineTech2023.tsx
We want to add zod schema on all our remotion templates
Add default schema for showcase with "basic" props :
```
{
title,
speakers,
date,
time,
location,
}
```
Check diff or clone the branch to check the Remotion studio
=> feat(showcase): adding zod type for showcases with default values

remotion/compositions/showcases/campingDesSpeakers/components/Speakers.tsx, remotion/compositions/showcases/devfestLille/Speakers.tsx, remotion/compositions/showcases/devfestNantes/Speakers.tsx, remotion/compositions/showcases/volcamp/components/Speakers.tsx, remotion/design/molecules/AvatarWithCaption.tsx
To prevent having an error when adding a new speaker without src image url when editing the video from the studio we have to set a default src
Adding a default src image
Check code
=> fix(#976): add default Img src for speaker picture

app/templates/talks/talk/page.tsx, src/app/forms/Form.tsx
think fourth input should be as type of number because there user enter size of title, so that is why i wanted to change it to number
just by adding "type" to places where it needed
by going through templates/talks/talk
=> fix(app): add type to input

app/templates/talks/talk/page.tsx, remotion/compositions/templates/talk/SpeakerAndTitle.tsx, remotion/compositions/templates/talk/Talk.tsx, remotion/compositions/templates/talk/Talks.composition.tsx, remotion/compositions/templates/talk/talks.types.ts, src/app/forms/Form.tsx, src/app/hooks/useInputChange.ts, src/data/config/compositionsConfig.ts, src/data/config/templates/talkConfig.ts
Add a color input to change the text color of the speaker name in the Talk template (Fix #1140)
Try to change color on the preview
=> feat(template/Talk): adding color picker on talk template

remotion/compositions/templates/meetup/Meetup.composition.tsx, remotion/compositions/templates/meetup/Meetup.tsx, remotion/compositions/templates/talk/Talk.tsx, remotion/compositions/templates/talk/Talks.composition.tsx, remotion/compositions/templates/talk/talks.types.ts, remotion/design/atoms/EventLogo.tsx
I need to prepare some meetup announcement posts for LyonJS but Meetup and Talk compositions were broken.
- force loading of open font 
- EventLogo now handle external logo url (it was not)
- Use Talk Schema as type
- Create meetup schema and use it as type
- pass all default variable as props of composition to help on the studio
- run remotion start locally
=> refactor(compositions): enhance Meetup and Talk compositions
